/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Funcionamiento;

import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.net.URL;

/**
 *
 * @author Laboratorios
 */
public class Juego extends javax.swing.JPanel {
    //URL direccionSonidoSalto,direccionSonidoChoque;
    //AudioClip sonidoChoque,sonidoSalto;
    
    Personaje personaje=new Personaje(this);
    Fondo fondo=new Fondo(this);
    
    static boolean juegoFinalizado=false;
    static boolean pierdeVida=false;
    static int vidas=3;
    static int puntos=0;
    static int nivel=1;
    private String nombre;
    /**
     * Creates new form Juego
     */
    public Juego(String nombre) {
        this.nombre=nombre;
        this.setSize(1000,856);
        this.setLocation(70,200);
        this.setVisible(true);
        //direccionSonidoChoque=getClass().getResource("");
        addKeyListener(new KeyListener(){
            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
                
                //sonidoSalto.play();
                personaje.keyPressed(ke);
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                personaje.keyReleased(ke);
            }
            
        });
        setFocusable(true);
    }
    
    public void mover(){
        
        personaje.mover();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2 =(Graphics2D) g;
        dibujar(g2);
        dibujarPuntaje(g2);
    }
    
    public void dibujar(Graphics2D g){
        fondo.paint(g);
        personaje.paint(g);
        
        mover();
    }
    
    public void dibujarPuntaje(Graphics2D g){
        Graphics2D g1=g,g2=g;
        Font score =new Font("Arial",Font.BOLD,30);
        g.setFont(score);
        g.setColor(Color.blue);
        g1.drawString("Puntaje: "+puntos,500 ,30 );
        g1.drawString("Vidas: "+vidas,20 ,30 );
        g1.drawString("Usuario: "+nombre,300 ,30 );
        if(juegoFinalizado){
            g2.setColor(Color.yellow);
            g2.drawString("Haz perdido", ((float)getBounds().getCenterX()/2)+170, 70);
        }
    }
    
    public void finJuego(){
        juegoFinalizado=true;
        //sonidoChoque.play();
    }
    
    public void pierde(){
        //sonidoChoque.play();
        pierdeVida=true;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
