/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frms;

import ManejoDeDatos.Usuario;

/**
 *
 * @author USER
 */
public class GameOver extends javax.swing.JFrame {
Usuario usuario;
    /**
     * Creates new form GameOver
     */
    public GameOver(Usuario usuario) {
        this.usuario=usuario;
        initComponents();
        this.setVisible(true);
        this.setSize(1000,856);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        volverJugar = new javax.swing.JToggleButton();
        salirButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/GameOver.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        volverJugar.setText("jToggleButton1");
        volverJugar.setBorderPainted(false);
        volverJugar.setContentAreaFilled(false);
        volverJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverJugarActionPerformed(evt);
            }
        });
        getContentPane().add(volverJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 440, 60));

        salirButton.setContentAreaFilled(false);
        salirButton.setDefaultCapable(false);
        salirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirButtonActionPerformed(evt);
            }
        });
        getContentPane().add(salirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 620, 180, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverJugarActionPerformed
        // TODO add your handling code here:
        DatosUsuario datosUsuario=new DatosUsuario(usuario);
        this.dispose();
    }//GEN-LAST:event_volverJugarActionPerformed

    private void salirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirButtonActionPerformed
        // TODO add your handling code here:
        PantallaPrincipal pantallaPrincipal=new PantallaPrincipal();
        this.dispose();
    }//GEN-LAST:event_salirButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salirButton;
    private javax.swing.JToggleButton volverJugar;
    // End of variables declaration//GEN-END:variables
}
