/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frms;

import Funcionamiento.HiloEjecucion;
import Funcionamiento.Juego;
import ManejoDeDatos.ManejoDeUsuario;
import ManejoDeDatos.Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class InicioSesion extends javax.swing.JFrame {
    ManejoDeUsuario manejoDeUsuarios=new ManejoDeUsuario();
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setVisible(true);
        this.setSize(1000,856);
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioTextField = new javax.swing.JTextField();
        contrasenaTextField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        inicioSesionButton = new javax.swing.JButton();
        registrarseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 856));
        setPreferredSize(new java.awt.Dimension(1000, 856));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(usuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 320, 50));
        getContentPane().add(contrasenaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 320, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/EL chef comelon.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        inicioSesionButton.setText("Iniciar Sesion");
        inicioSesionButton.setBorderPainted(false);
        inicioSesionButton.setContentAreaFilled(false);
        inicioSesionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioSesionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(inicioSesionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 560, 370, 50));

        registrarseButton.setText("Registrarse");
        registrarseButton.setBorderPainted(false);
        registrarseButton.setContentAreaFilled(false);
        registrarseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registrarseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 690, 360, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseButtonActionPerformed
        // TODO add your handling code here:
        Registrarse registrarse=new Registrarse();
        this.dispose();
    }//GEN-LAST:event_registrarseButtonActionPerformed

    private void inicioSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioSesionButtonActionPerformed
        // TODO add your handling code here:
        try {
            Usuario usuarioTemp = new Usuario(usuarioTextField.getText(), contrasenaTextField.getText());
            Usuario usuario = manejoDeUsuarios.buscarUsuario(usuarioTemp);

            if (usuario != null) {
                JFrame ventana = new JFrame("Cocina");
                Juego cocina = new Juego(usuarioTextField.getText());
                ventana.setSize(1000, 856);
                ventana.setLocation(70, 200);
                ventana.add(cocina);
                ventana.setLocationRelativeTo(null);
                ventana.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                ventana.setVisible(true);
                Thread thread = new Thread(new HiloEjecucion(cocina));
                thread.start();
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_inicioSesionButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField contrasenaTextField;
    private javax.swing.JButton inicioSesionButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton registrarseButton;
    private javax.swing.JTextField usuarioTextField;
    // End of variables declaration//GEN-END:variables
}
