/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frms;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        this.setVisible(true);
        this.setSize(1000,856);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PantallaPrincipal = new javax.swing.JLabel();
        Jugar = new javax.swing.JButton();
        AcercaDeButton = new javax.swing.JButton();
        ayudaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        PantallaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/pantallaPrincipal.png"))); // NOI18N
        getContentPane().add(PantallaPrincipal);
        PantallaPrincipal.setBounds(0, 0, 1000, 856);

        Jugar.setBorderPainted(false);
        Jugar.setContentAreaFilled(false);
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });
        getContentPane().add(Jugar);
        Jugar.setBounds(630, 400, 180, 50);

        AcercaDeButton.setText("jButton1");
        AcercaDeButton.setBorderPainted(false);
        AcercaDeButton.setContentAreaFilled(false);
        AcercaDeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(AcercaDeButton);
        AcercaDeButton.setBounds(580, 620, 280, 50);

        ayudaButton.setText("jButton1");
        ayudaButton.setBorderPainted(false);
        ayudaButton.setContentAreaFilled(false);
        ayudaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ayudaButton);
        ayudaButton.setBounds(630, 500, 180, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
        InicioSesion inicioSesion=new  InicioSesion();
        this.dispose();
        
        
    }//GEN-LAST:event_JugarActionPerformed

    private void AcercaDeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Este juego fue creado por:\n-Jesús Tapia\n-Alexa Picos\n-Kimberly Martínez");
    }//GEN-LAST:event_AcercaDeButtonActionPerformed

    private void ayudaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaButtonActionPerformed
        // TODO add your handling code here:
        ComoJugar comoJugar=new ComoJugar();
        this.dispose();
    }//GEN-LAST:event_ayudaButtonActionPerformed
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcercaDeButton;
    private javax.swing.JButton Jugar;
    private javax.swing.JLabel PantallaPrincipal;
    private javax.swing.JButton ayudaButton;
    // End of variables declaration//GEN-END:variables
}
