/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frms;

import ManejoDeDatos.ManejoDeUsuario;
import ManejoDeDatos.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class Registrarse extends javax.swing.JFrame {
    ManejoDeUsuario manejoDeUsuario=new ManejoDeUsuario();

    /**
     * Creates new form InicioSesion
     */
    public Registrarse() {
        initComponents();
        this.setVisible(true);
        this.setSize(1000,856);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuarioTextField = new javax.swing.JTextField();
        contrasenaTextField = new javax.swing.JPasswordField();
        confirmaContrasenaTextField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        registrarseButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 856));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(usuarioTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 270, 40));
        getContentPane().add(contrasenaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 270, 40));
        getContentPane().add(confirmaContrasenaTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 270, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Multimedia/ElChefComelonRegistro.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        registrarseButton.setText("Registrarse");
        registrarseButton.setContentAreaFilled(false);
        registrarseButton.setDefaultCapable(false);
        registrarseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(registrarseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 690, 360, 40));

        volverButton.setText("Volver");
        volverButton.setBorderPainted(false);
        volverButton.setContentAreaFilled(false);
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });
        getContentPane().add(volverButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 780, 190, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        // TODO add your handling code here:
        InicioSesion inicioSesion=new InicioSesion();
        this.dispose();
    }//GEN-LAST:event_volverButtonActionPerformed

    private void registrarseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseButtonActionPerformed
        // TODO add your handling code here:
        if(usuarioTextField.getText().equals("") ||contrasenaTextField.getText().equals("") || confirmaContrasenaTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Rellene todos los campos");
        } else {
            try {
                Usuario usuario = new Usuario(usuarioTextField.getText(), contrasenaTextField.getText());
                manejoDeUsuario.validarContrasena(contrasenaTextField.getText());
                manejoDeUsuario.comprobarUsuarioRegistrado(usuario);
                if (!contrasenaTextField.getText().equals(contrasenaTextField.getText())) {
                    JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden");
                } else {
                    manejoDeUsuario.guardarNuevoUsuario(usuario);
                    this.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_registrarseButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmaContrasenaTextField1;
    private javax.swing.JPasswordField contrasenaTextField;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton registrarseButton;
    private javax.swing.JTextField usuarioTextField;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
